// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $ai_models from "./routes/ai-models.tsx";
import * as $index from "./routes/index.tsx";
import * as $weekly_slug_ from "./routes/weekly/[slug].tsx";
import * as $FilterTabs from "./islands/FilterTabs.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/ai-models.tsx": $ai_models,
    "./routes/index.tsx": $index,
    "./routes/weekly/[slug].tsx": $weekly_slug_,
  },
  islands: {
    "./islands/FilterTabs.tsx": $FilterTabs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
